apiVersion: v2
name: minecraft-server
description: A flexible Helm chart to run a Minecraft Java Edition server
type: application
version: 0.1.0
home: "https://github.com/clucktopia"
sources:
  - "https://github.com/itzg/docker-minecraft-server"
maintainers:
  - name: iveahugeship
    email: iveahugeship@gmail.com
dependencies:
  - name: minecraft-lib
    version: ~0.0.0
    repository: "https://clucktopia.github.io/helm-charts"
